/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

/**
 *
 * @author matheus.rvieira5
 */
public class NewMenuView extends javax.swing.JPanel {

    /** Creates new form NewMenuView */
    public NewMenuView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topoMenu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        biblioteca1 = new javax.swing.JLabel();
        fundoLaranja1 = new javax.swing.JPanel();
        biblioteca3 = new javax.swing.JLabel();
        botaoAcervo1 = new javax.swing.JButton();
        fundoLaranja2 = new javax.swing.JPanel();
        biblioteca4 = new javax.swing.JLabel();
        botaoAcervo2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 85, 48));
        setForeground(new java.awt.Color(255, 85, 48));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel1.setBackground(new java.awt.Color(255, 85, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 100));

        topoMenu.setBackground(new java.awt.Color(255, 255, 255));
        topoMenu.setPreferredSize(new java.awt.Dimension(1600, 100));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo.png"))); // NOI18N
        logo.setToolTipText("");
        logo.setPreferredSize(new java.awt.Dimension(50, 50));

        biblioteca1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        biblioteca1.setForeground(new java.awt.Color(255, 169, 13));
        biblioteca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biblioteca1.setText("BIBLIOTECA");
        biblioteca1.setToolTipText("Biblioteca");
        biblioteca1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        biblioteca1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout topoMenuLayout = new javax.swing.GroupLayout(topoMenu);
        topoMenu.setLayout(topoMenuLayout);
        topoMenuLayout.setHorizontalGroup(
            topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoMenuLayout.createSequentialGroup()
                .addContainerGap(801, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(627, 627, 627))
            .addGroup(topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topoMenuLayout.createSequentialGroup()
                    .addGap(534, 534, 534)
                    .addComponent(biblioteca1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(807, Short.MAX_VALUE)))
        );
        topoMenuLayout.setVerticalGroup(
            topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topoMenuLayout.createSequentialGroup()
                    .addContainerGap(151, Short.MAX_VALUE)
                    .addComponent(biblioteca1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(82, 82, 82)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topoMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(topoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fundoLaranja1.setBackground(new java.awt.Color(255, 169, 13));
        fundoLaranja1.setToolTipText("");
        fundoLaranja1.setPreferredSize(new java.awt.Dimension(1600, 800));

        biblioteca3.setBackground(new java.awt.Color(255, 169, 13));
        biblioteca3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        biblioteca3.setForeground(new java.awt.Color(255, 255, 255));
        biblioteca3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biblioteca3.setText("Cadastro de novos \ntítulos e consulta");
        biblioteca3.setToolTipText("Biblioteca");
        biblioteca3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        biblioteca3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        biblioteca3.setOpaque(true);

        botaoAcervo1.setBackground(new java.awt.Color(255, 169, 13));
        botaoAcervo1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botaoAcervo1.setForeground(new java.awt.Color(255, 255, 255));
        botaoAcervo1.setText("Acervo");
        botaoAcervo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAcervo1.setOpaque(false);

        javax.swing.GroupLayout fundoLaranja1Layout = new javax.swing.GroupLayout(fundoLaranja1);
        fundoLaranja1.setLayout(fundoLaranja1Layout);
        fundoLaranja1Layout.setHorizontalGroup(
            fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLaranja1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(biblioteca3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(botaoAcervo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1036, Short.MAX_VALUE))
        );
        fundoLaranja1Layout.setVerticalGroup(
            fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLaranja1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(botaoAcervo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biblioteca3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        fundoLaranja2.setBackground(new java.awt.Color(255, 169, 13));
        fundoLaranja2.setToolTipText("");
        fundoLaranja2.setPreferredSize(new java.awt.Dimension(1600, 800));

        biblioteca4.setBackground(new java.awt.Color(255, 169, 13));
        biblioteca4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        biblioteca4.setForeground(new java.awt.Color(255, 255, 255));
        biblioteca4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biblioteca4.setText("Cadastro de novos \ntítulos e consulta");
        biblioteca4.setToolTipText("Biblioteca");
        biblioteca4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        biblioteca4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        biblioteca4.setOpaque(true);

        botaoAcervo2.setBackground(new java.awt.Color(255, 169, 13));
        botaoAcervo2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botaoAcervo2.setForeground(new java.awt.Color(255, 255, 255));
        botaoAcervo2.setText("Acervo");
        botaoAcervo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAcervo2.setOpaque(false);

        javax.swing.GroupLayout fundoLaranja2Layout = new javax.swing.GroupLayout(fundoLaranja2);
        fundoLaranja2.setLayout(fundoLaranja2Layout);
        fundoLaranja2Layout.setHorizontalGroup(
            fundoLaranja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLaranja2Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(fundoLaranja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(biblioteca4, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(botaoAcervo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1036, Short.MAX_VALUE))
        );
        fundoLaranja2Layout.setVerticalGroup(
            fundoLaranja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLaranja2Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(botaoAcervo2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biblioteca4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fundoLaranja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundoLaranja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1616, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fundoLaranja1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fundoLaranja2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biblioteca1;
    private javax.swing.JLabel biblioteca3;
    private javax.swing.JLabel biblioteca4;
    private javax.swing.JButton botaoAcervo1;
    private javax.swing.JButton botaoAcervo2;
    private javax.swing.JPanel fundoLaranja1;
    private javax.swing.JPanel fundoLaranja2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel topoMenu;
    // End of variables declaration//GEN-END:variables

}
