/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

/**
 *
 * @author matheus.rvieira5
 */
public class NewMenuView extends javax.swing.JPanel {

    /** Creates new form NewMenuView */
    public NewMenuView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topoMenu = new javax.swing.JPanel();
        biblioteca = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fundoLaranja = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 85, 48));
        setForeground(new java.awt.Color(255, 85, 48));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel1.setBackground(new java.awt.Color(255, 85, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 100));

        topoMenu.setBackground(new java.awt.Color(255, 255, 255));
        topoMenu.setPreferredSize(new java.awt.Dimension(1600, 100));

        biblioteca.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        biblioteca.setForeground(new java.awt.Color(255, 169, 13));
        biblioteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biblioteca.setText("BIBLIOTECA");
        biblioteca.setToolTipText("Biblioteca");
        biblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        biblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Logo.png"))); // NOI18N
        logo.setToolTipText("");
        logo.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout topoMenuLayout = new javax.swing.GroupLayout(topoMenu);
        topoMenu.setLayout(topoMenuLayout);
        topoMenuLayout.setHorizontalGroup(
            topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoMenuLayout.createSequentialGroup()
                .addContainerGap(524, Short.MAX_VALUE)
                .addComponent(biblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(627, 627, 627))
        );
        topoMenuLayout.setVerticalGroup(
            topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topoMenuLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(biblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(topoMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fundoLaranja.setBackground(new java.awt.Color(255, 85, 48));
        fundoLaranja.setPreferredSize(new java.awt.Dimension(1600, 800));

        javax.swing.GroupLayout fundoLaranjaLayout = new javax.swing.GroupLayout(fundoLaranja);
        fundoLaranja.setLayout(fundoLaranjaLayout);
        fundoLaranjaLayout.setHorizontalGroup(
            fundoLaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        fundoLaranjaLayout.setVerticalGroup(
            fundoLaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundoLaranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fundoLaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biblioteca;
    private javax.swing.JPanel fundoLaranja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel topoMenu;
    // End of variables declaration//GEN-END:variables

}
