/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

/**
 *
 * @author matheus.rvieira5
 */
public class NewMenuView extends javax.swing.JPanel {

    /** Creates new form NewMenuView */
    public NewMenuView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topoMenu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        biblioteca1 = new javax.swing.JLabel();
        fundoLaranja1 = new javax.swing.JPanel();
        stringBotaoAcervo = new javax.swing.JLabel();
        botaoAcervo1 = new javax.swing.JButton();
        botaoAcervo3 = new javax.swing.JButton();
        botaoAcervo4 = new javax.swing.JButton();
        stringBotaoEmprestimos = new javax.swing.JLabel();
        stringBotaoLeitores = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 85, 48));
        setForeground(new java.awt.Color(255, 85, 48));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel1.setBackground(new java.awt.Color(255, 85, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 100));

        topoMenu.setBackground(new java.awt.Color(255, 255, 255));
        topoMenu.setPreferredSize(new java.awt.Dimension(1600, 100));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo.png"))); // NOI18N
        logo.setToolTipText("");
        logo.setPreferredSize(new java.awt.Dimension(50, 50));

        biblioteca1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        biblioteca1.setForeground(new java.awt.Color(255, 169, 13));
        biblioteca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biblioteca1.setText("BIBLIOTECA");
        biblioteca1.setToolTipText("Biblioteca");
        biblioteca1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        biblioteca1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout topoMenuLayout = new javax.swing.GroupLayout(topoMenu);
        topoMenu.setLayout(topoMenuLayout);
        topoMenuLayout.setHorizontalGroup(
            topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoMenuLayout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .addComponent(biblioteca1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(627, 627, 627))
        );
        topoMenuLayout.setVerticalGroup(
            topoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topoMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(biblioteca1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topoMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(topoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fundoLaranja1.setBackground(new java.awt.Color(204, 204, 204));
        fundoLaranja1.setToolTipText("");
        fundoLaranja1.setPreferredSize(new java.awt.Dimension(1600, 800));

        stringBotaoAcervo.setBackground(new java.awt.Color(255, 169, 13));
        stringBotaoAcervo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        stringBotaoAcervo.setForeground(new java.awt.Color(255, 255, 255));
        stringBotaoAcervo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stringBotaoAcervo.setText("Cadastro de novos \ntítulos e consulta");
        stringBotaoAcervo.setToolTipText("Biblioteca");
        stringBotaoAcervo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stringBotaoAcervo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stringBotaoAcervo.setOpaque(true);

        botaoAcervo1.setBackground(new java.awt.Color(255, 169, 13));
        botaoAcervo1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botaoAcervo1.setForeground(new java.awt.Color(255, 255, 255));
        botaoAcervo1.setText("Acervo");
        botaoAcervo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAcervo1.setOpaque(false);

        botaoAcervo3.setBackground(new java.awt.Color(255, 169, 13));
        botaoAcervo3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botaoAcervo3.setForeground(new java.awt.Color(255, 255, 255));
        botaoAcervo3.setText("Empréstimos");
        botaoAcervo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAcervo3.setOpaque(false);

        botaoAcervo4.setBackground(new java.awt.Color(255, 169, 13));
        botaoAcervo4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botaoAcervo4.setForeground(new java.awt.Color(255, 255, 255));
        botaoAcervo4.setText("Leitores");
        botaoAcervo4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAcervo4.setOpaque(false);
        botaoAcervo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcervo4ActionPerformed(evt);
            }
        });

        stringBotaoEmprestimos.setBackground(new java.awt.Color(255, 169, 13));
        stringBotaoEmprestimos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        stringBotaoEmprestimos.setForeground(new java.awt.Color(255, 255, 255));
        stringBotaoEmprestimos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stringBotaoEmprestimos.setText("Realizar novo empréstimo, consultar pendências");
        stringBotaoEmprestimos.setToolTipText("Biblioteca");
        stringBotaoEmprestimos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stringBotaoEmprestimos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stringBotaoEmprestimos.setOpaque(true);

        stringBotaoLeitores.setBackground(new java.awt.Color(255, 169, 13));
        stringBotaoLeitores.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        stringBotaoLeitores.setForeground(new java.awt.Color(255, 255, 255));
        stringBotaoLeitores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stringBotaoLeitores.setText("\nCadastro de novos  assistidos, colaboradores, moradores e consulta");
        stringBotaoLeitores.setToolTipText("Biblioteca");
        stringBotaoLeitores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stringBotaoLeitores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stringBotaoLeitores.setOpaque(true);

        javax.swing.GroupLayout fundoLaranja1Layout = new javax.swing.GroupLayout(fundoLaranja1);
        fundoLaranja1.setLayout(fundoLaranja1Layout);
        fundoLaranja1Layout.setHorizontalGroup(
            fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLaranja1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stringBotaoAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(botaoAcervo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAcervo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stringBotaoLeitores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stringBotaoEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAcervo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(262, 262, 262))
        );
        fundoLaranja1Layout.setVerticalGroup(
            fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLaranja1Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAcervo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAcervo4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAcervo3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fundoLaranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stringBotaoAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stringBotaoEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stringBotaoLeitores, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundoLaranja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundoLaranja1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAcervo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcervo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAcervo4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biblioteca1;
    private javax.swing.JButton botaoAcervo1;
    private javax.swing.JButton botaoAcervo3;
    private javax.swing.JButton botaoAcervo4;
    private javax.swing.JPanel fundoLaranja1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel stringBotaoAcervo;
    private javax.swing.JLabel stringBotaoEmprestimos;
    private javax.swing.JLabel stringBotaoLeitores;
    private javax.swing.JPanel topoMenu;
    // End of variables declaration//GEN-END:variables

}
